baseURL = "/baseline-model/"
languageCode = "en-us"
title = "Baseline Model"
uglyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  ratings = "/:year/:month/:day/ratings"
  predictions = "/:year/:month/:day/predictions"

[taxonomies]
  tag = ""
  category = ""
