baseURL = "https://baseline-model.s3.amazonaws.com"
languageCode = "en-us"
title = "BaseLine Model"
uglyURLs = true

[permalinks]
  ratings = "/:year/:month/:day/ratings"
  predictions = "/:year/:month/:day/predictions"

[taxonomies]
  tag = ""
  category = ""
