baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
uglyURLs = true
[permalinks]
  ratings = "/:year/:month/:day/ratings"
  predictions = "/:year/:month/:day/predictions"
[taxonomies]
  tag = ""
  category = ""
